apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aaa
    app.kubernetes.io/part-of: aaa
  name: aaa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: aaa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: aaa
    spec:
      containers:
      - image: quay.io/hacdev/user1-tenant/aaa/aaa@sha256:a4bbbf7935cb23360e72539eaa5339e59cd415b6868587c778c33e8188d0f45b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
