apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aaa
    app.kubernetes.io/part-of: aaa
  name: aaa
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: aaa
status:
  loadBalancer: {}
