apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: aaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/user1-tenant/aaa/aaa@sha256:6b115604019f437e982b9784c77885055719a4401d31b46686f1eaf3526d9119
        name: my-java-quarkus
        resources: {}
status: {}
