apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aaa
    app.kubernetes.io/part-of: aaa
  name: aaai3gm
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: aaa
    weight: null
status: {}
